#!/usr/bin/python

#EcoDroidLink: modified to continue NAP forever and changed NetworkServer to NetworkServer1 to make it work - from bluez-5.7/test/test-nap

from __future__ import absolute_import, print_function, unicode_literals

import sys
import time
import dbus
from optparse import OptionParser, make_option
import bluezutils
import logging
import logging.handlers

logger = logging.getLogger('edl_nap')
logger.setLevel(logging.DEBUG)
handler = logging.handlers.SysLogHandler(address = '/dev/log')
logger.addHandler(handler)

def printlog(s):
    logger.info(s)
    print(s)

bus = dbus.SystemBus()

option_list = [
		make_option("-i", "--device", action="store",
				type="string", dest="dev_id"),
		]
parser = OptionParser(option_list=option_list)

(options, args) = parser.parse_args()

adapter_path = bluezutils.find_adapter(options.dev_id).object_path
server = dbus.Interface(bus.get_object("org.bluez", adapter_path),
						"org.bluez.NetworkServer1")

service = "nap"

if (len(args) < 1):
	bridge = "tether"
else:
	bridge = args[0]

server.Register(service, bridge)

printlog("Server for %s registered for %s" % (service, bridge))

try:
	while (1):
		time.sleep(30)
	#run forever - control shold never reach here
	printlog("Terminating connection")
except:
	pass

server.Unregister(service)
